use DBA
go

DECLARE @dataInicio VARCHAR(20), @dataFim VARCHAR(20),
		@diaFim INT

SELECT @dataInicio = LEFT(CONVERT(VARCHAR, DATEADD(month, -1, GETDATE()), 112), 6) + '01'

SET @diaFim = 31

WHILE @diaFim > 0
BEGIN
	SET @dataFim = LEFT(CONVERT(VARCHAR, DATEADD(month, -1, GETDATE()), 112), 6) + RIGHT('0'+CONVERT(VARCHAR, @diaFim), 2) + ' 23:59'
	IF ISDATE(@dataFim) = 1
		SET @diaFim = 0
	ELSE
		SET @diaFim = @diaFim - 1
END

SELECT DATA, REPLACE (CONVERT (VARCHAR(30), SUM (FILESIZEMB)), '.', ',') ALLOCATEDMB, 
			 REPLACE (CONVERT (VARCHAR(30), SUM (FREESPACEMB)), '.', ',') FREESPACEMB
--SELECT DATA, SUM (FILESIZEMB) ALLOCATEDMB, SUM(FREESPACEMB) FREESPACEMB
FROM (
	SELECT 
		CONVERT (VARCHAR, data, 103) DATA,
		DATABASENAME, 
		FILESIZEMB,
		FREESPACEMB
	FROM dbo.DBA_INFO_DATABASE
	WHERE 
	data BETWEEN @dataInicio AND @dataFim
	AND PHYSICALFILENAME NOT LIKE '%.LDF'
) TBL
GROUP BY DATA