USE dba
	DECLARE @DIAS INT,  -- DIAS PARA ANÁLISE DA MÉDIA DE CRESCIMENTO
			@THRESHOLD INT, -- DIAS LIMITE PARA CRESCIMENTO
			@MARGEM NUMERIC(9,2), -- (%) MARGEM DO CRESCIMENTO (**FORMATO = 1.2 PARA 20%)
		    @CUSTOMER_NAME VARCHAR(100),
		    @SERVER_NAME VARCHAR(100)
	
  SELECT @DIAS =   90,
		 @MARGEM =   1.1

	SELECT	@@SERVERNAME [Server], DRIVE [Drive], REPLACE (CONVERT (VARCHAR, FREEMB), '.', ',') [Área Livre Atual], 
			REPLACE (CONVERT (VARCHAR, AVG_MB), '.', ',') [Média Cresc. Diário],
			FLOOR(FREEMB / (AVG_MB * @MARGEM)) [Dias Restantes]
	FROM dbo.DBA_INFO_FILESYSTEM FS
	INNER JOIN (
		SELECT UNIDADE, SUM (PCTG) [PCTG], SUM (CRESCIMENTO) / @DIAS AVG_MB
		FROM (
			SELECT	D1.DATA, D1.UNIDADE, D1.ESPACO SPC1, D2.ESPACO SPC2, 
					((D1.ESPACO - D2.ESPACO) * 100) / D2.ESPACO PCTG,
					D1.ESPACO - D2.ESPACO CRESCIMENTO
			FROM (
				SELECT DATA, LEFT (PHYSICALFILENAME, 1) UNIDADE, SUM (FILESIZEMB /*- FREESPACEMB*/) ESPACO
				FROM DBO.DBA_INFO_DATABASE
				WHERE DATA >= (CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 112))-@DIAS)
				GROUP BY LEFT (PHYSICALFILENAME, 1), DATA
			) D1
			INNER JOIN (
				SELECT DATA, LEFT (PHYSICALFILENAME, 1) UNIDADE, SUM (FILESIZEMB /*- FREESPACEMB*/) ESPACO
				FROM DBO.DBA_INFO_DATABASE
				WHERE DATA >= (CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 112))-(@DIAS+1))
				GROUP BY LEFT (PHYSICALFILENAME, 1), DATA
			) D2 ON D1.DATA = D2.DATA + 1 AND D1.UNIDADE = D2.UNIDADE
		) TBL
		GROUP BY UNIDADE
	) GR ON FS.DRIVE = GR.UNIDADE
	WHERE DATA = CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 112))-1
		--AND FLOOR(FREEMB / (AVG_MB * @MARGEM)) < @THRESHOLD
		AND AVG_MB > 0
		AND FLOOR(FREEMB / (AVG_MB * @MARGEM)) >= 0
