SELECT D1.DATABASENAME, D1.LOGICALFILENAME, D1.PHYSICALFILENAME,
    D1.DATA, D1.FILESIZEMB,D2.DATA,D2.FILESIZEMB, D1.FILESIZEMB-D2.FILESIZEMB AS CRESMB -- SIZEMB
    --D1.DATA, D1.FILESIZEMB/1024 AS FILESIZEGB,D2.DATA,D2.FILESIZEMB/1024 AS FILESIZEGB, (D1.FILESIZEMB-D2.FILESIZEMB)/1024 AS CRESGB -- SIZEGB
    
FROM
(SELECT DATA, DATABASENAME, LOGICALFILENAME, FILESIZEMB, PHYSICALFILENAME
	FROM DBA..DBA_INFO_DATABASE
) AS D1 INNER JOIN
(SELECT DATA, DATABASENAME, LOGICALFILENAME, FILESIZEMB, PHYSICALFILENAME
	FROM DBA..DBA_INFO_DATABASE
) AS D2 ON
	D1.DATA=D2.DATA+1 AND
	D1.DATABASENAME=D2.DATABASENAME AND
	D1.LOGICALFILENAME=D2.LOGICALFILENAME AND
	D1.PHYSICALFILENAME=D2.PHYSICALFILENAME
WHERE D1.FILESIZEMB > D2.FILESIZEMB
	--AND D1.PHYSICALFILENAME LIKE 'V:\%' -- Filtro por Drive
        --AND D1.DATABASENAME IN ('crm','cep','plusinfo') -- Filtro por DB
ORDER BY D1.DATA DESC
