USE [DBA]
GO

SELECT	
		'USE ['+DATABASENAME+']','GO',
		'DBCC SHRINKFILE ('''+LOGICALFILENAME+''', 0, TRUNCATEONLY)','GO',
		'DBCC SHRINKFILE ('''+LOGICALFILENAME+''', 0, NOTRUNCATE)','GO',
		'DBCC SHRINKFILE ('''+LOGICALFILENAME+''', 0, TRUNCATEONLY)','GO'
FROM DBA_INFO_DATABASE
WHERE FILESIZEMB >= 7000 AND
	DATA = CONVERT(DATE,GETDATE()) AND
	LOGICALFILENAME NOT LIKE '%temp%' AND
	PHYSICALFILENAME LIKE '%log%' AND
	RECOVERYMODE = 'SIMPLE'
GO
